/* tslint:disable */
/* eslint-disable */
/**
 * e-book-merge
 * 電子書籍を一元管理
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGmailApiOAuth2TokenResponse
 */
export interface CreateGmailApiOAuth2TokenResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateGmailApiOAuth2TokenResponse
     */
    id?: number;
}

export function CreateGmailApiOAuth2TokenResponseFromJSON(json: any): CreateGmailApiOAuth2TokenResponse {
    return CreateGmailApiOAuth2TokenResponseFromJSONTyped(json, false);
}

export function CreateGmailApiOAuth2TokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGmailApiOAuth2TokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function CreateGmailApiOAuth2TokenResponseToJSON(value?: CreateGmailApiOAuth2TokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

