/* tslint:disable */
/* eslint-disable */
/**
 * e-book-merge
 * 電子書籍を一元管理
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGmailApiOAuth2TokenRequest
 */
export interface CreateGmailApiOAuth2TokenRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateGmailApiOAuth2TokenRequest
     */
    code: string;
    /**
     * 
     * @type {number}
     * @memberof CreateGmailApiOAuth2TokenRequest
     */
    userId: number;
}

export function CreateGmailApiOAuth2TokenRequestFromJSON(json: any): CreateGmailApiOAuth2TokenRequest {
    return CreateGmailApiOAuth2TokenRequestFromJSONTyped(json, false);
}

export function CreateGmailApiOAuth2TokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGmailApiOAuth2TokenRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'userId': json['user_id'],
    };
}

export function CreateGmailApiOAuth2TokenRequestToJSON(value?: CreateGmailApiOAuth2TokenRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'user_id': value.userId,
    };
}

