/* tslint:disable */
/* eslint-disable */
/**
 * e-book-merge
 * 電子書籍を一元管理
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EbookService,
    EbookServiceFromJSON,
    EbookServiceFromJSONTyped,
    EbookServiceToJSON,
} from './EbookService';

/**
 * 
 * @export
 * @interface Ebook
 */
export interface Ebook {
    /**
     * 
     * @type {number}
     * @memberof Ebook
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Ebook
     */
    title?: string;
    /**
     * 
     * @type {EbookService}
     * @memberof Ebook
     */
    ebookService?: EbookService;
}

export function EbookFromJSON(json: any): Ebook {
    return EbookFromJSONTyped(json, false);
}

export function EbookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ebook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'ebookService': !exists(json, 'ebook_service') ? undefined : EbookServiceFromJSON(json['ebook_service']),
    };
}

export function EbookToJSON(value?: Ebook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'ebook_service': EbookServiceToJSON(value.ebookService),
    };
}

