/* tslint:disable */
/* eslint-disable */
/**
 * e-book-merge
 * 電子書籍を一元管理
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EbookService
 */
export interface EbookService {
    /**
     * 
     * @type {number}
     * @memberof EbookService
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EbookService
     */
    name?: string;
}

export function EbookServiceFromJSON(json: any): EbookService {
    return EbookServiceFromJSONTyped(json, false);
}

export function EbookServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): EbookService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function EbookServiceToJSON(value?: EbookService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

