/* tslint:disable */
/* eslint-disable */
/**
 * e-book-merge
 * 電子書籍を一元管理
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Ebook,
    EbookFromJSON,
    EbookFromJSONTyped,
    EbookToJSON,
} from './Ebook';

/**
 * 
 * @export
 * @interface ListEbook
 */
export interface ListEbook {
    /**
     * 
     * @type {Array<Ebook>}
     * @memberof ListEbook
     */
    ebooks?: Array<Ebook>;
}

export function ListEbookFromJSON(json: any): ListEbook {
    return ListEbookFromJSONTyped(json, false);
}

export function ListEbookFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEbook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ebooks': !exists(json, 'ebooks') ? undefined : ((json['ebooks'] as Array<any>).map(EbookFromJSON)),
    };
}

export function ListEbookToJSON(value?: ListEbook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ebooks': value.ebooks === undefined ? undefined : ((value.ebooks as Array<any>).map(EbookToJSON)),
    };
}

