/* tslint:disable */
/* eslint-disable */
/**
 * e-book-merge
 * 電子書籍を一元管理
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuth2UserInfo
 */
export interface OAuth2UserInfo {
    /**
     * 
     * @type {string}
     * @memberof OAuth2UserInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2UserInfo
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OAuth2UserInfo
     */
    verifiedEmail?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OAuth2UserInfo
     */
    picture?: string;
}

export function OAuth2UserInfoFromJSON(json: any): OAuth2UserInfo {
    return OAuth2UserInfoFromJSONTyped(json, false);
}

export function OAuth2UserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuth2UserInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'verifiedEmail': !exists(json, 'verified_email') ? undefined : json['verified_email'],
        'picture': !exists(json, 'picture') ? undefined : json['picture'],
    };
}

export function OAuth2UserInfoToJSON(value?: OAuth2UserInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'verified_email': value.verifiedEmail,
        'picture': value.picture,
    };
}

