// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Ebook Ebook
//
// swagger:model Ebook
type Ebook struct {

	// ebook service
	EbookService *EbookService `json:"ebook_service,omitempty"`

	// id
	ID int64 `json:"id,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this ebook
func (m *Ebook) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEbookService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Ebook) validateEbookService(formats strfmt.Registry) error {
	if swag.IsZero(m.EbookService) { // not required
		return nil
	}

	if m.EbookService != nil {
		if err := m.EbookService.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ebook_service")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ebook_service")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this ebook based on the context it is used
func (m *Ebook) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEbookService(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Ebook) contextValidateEbookService(ctx context.Context, formats strfmt.Registry) error {

	if m.EbookService != nil {
		if err := m.EbookService.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ebook_service")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ebook_service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Ebook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ebook) UnmarshalBinary(b []byte) error {
	var res Ebook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
