// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GmailAPIConsentPageURL GmailApiConsentPageUrl
//
// swagger:model GmailApiConsentPageUrl
type GmailAPIConsentPageURL struct {

	// google concent page url
	// Required: true
	GoogleConcentPageURL *string `json:"google_concent_page_url"`
}

// Validate validates this gmail Api consent page Url
func (m *GmailAPIConsentPageURL) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGoogleConcentPageURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GmailAPIConsentPageURL) validateGoogleConcentPageURL(formats strfmt.Registry) error {

	if err := validate.Required("google_concent_page_url", "body", m.GoogleConcentPageURL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this gmail Api consent page Url based on context it is used
func (m *GmailAPIConsentPageURL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GmailAPIConsentPageURL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GmailAPIConsentPageURL) UnmarshalBinary(b []byte) error {
	var res GmailAPIConsentPageURL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
